Make monad-ledger blockwatch build again and add some functionality
The monad-ledger blockwatch example was failing to build with:

error: The default runtime flavor is `multi_thread`, but the `rt-multi-thread` feature is disabled.
  --> monad-ledger/examples/blockwatch.rs:37:1
   |
37 | #[tokio::main]
   | ^^^^^^^^^^^^^^
   |

Fix this by manually building a current_thread tokio runtime and running
the main function in that.

While we're at it, make the --debug mode no longer require passing in
the --ledger-path option, as it is not used in that mode, and extend it
to print the block that is being debugged:

$ cargo run -p monad-ledger --example blockwatch -- --debug ~/monad-bft/ledger/1
[...]
Block {
    header: Header {
        parent_hash: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
        ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347,
        beneficiary: 0x0000000000000000000000000000000000000000,
        state_root: 0x0000000000000000000000000000000000000000000000000000000000000000,
        transactions_root: 0x0000000000000000000000000000000000000000000000000000000000000000,
        receipts_root: 0x0000000000000000000000000000000000000000000000000000000000000000,
        withdrawals_root: Some(
            0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421,
        ),
        logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
        difficulty: 0x0_U256,
        number: 1,
        gas_limit: 1000000000,
        gas_used: 0,
        timestamp: 1724100737331,
        mix_hash: 0x0b73976c50ce44258653ae74340ebf82a6894a0d5a6abe52f02cfa2342c4719e,
        nonce: 0,
        base_fee_per_gas: Some(
            1000,
        ),
        blob_gas_used: None,
        excess_blob_gas: None,
        parent_beacon_block_root: None,
        extra_data: 0x,
    },
    body: [],
    ommers: [],
    withdrawals: Some(
        [],
    ),
}
seqnum: 1, tx count: 0, running hash: Hash(0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421)

The --ledger-path mode still works as before:

$ cargo run -p monad-ledger --example blockwatch -- --ledger-path ~/monad-bft/ledger/
[...]
seqnum: 37921, tx count: 0, running hash: 0xbbd128c20c5b33389621635b75a0474cdb4df5a82d3e61f91e20c9d3fe867fa2
seqnum: 37922, tx count: 0, running hash: 0xa8de1a96c0dd1a160a275b67110fc36dff67fffa53266293b29cd65d081b40b9
seqnum: 37923, tx count: 0, running hash: 0x751687b1fa0c09905037e0168f6c7b076911946fc43c22d737543e3da8429121
seqnum: 37924, tx count: 0, running hash: 0x72cf2704bbf89ae1aabc94c20a5d7f69c80a429ac8728369a47906dc3f398b17
seqnum: 37925, tx count: 0, running hash: 0x1202dd67e713c20cf2cbb58528345b92a706678a2aad9a21bdf26dcddae3fd58
seqnum: 37926, tx count: 0, running hash: 0xf68b5df547f722f37aa9db8c0b96357d19069a3ee49b15695ecbfbf82d0b2824
seqnum: 37927, tx count: 0, running hash: 0xc314e0cd7a47dbbe679d971d1c96d5d9416bc339f0fbb1c66deb913a14be8220