Fix EthBlockPolicy reset bug on statesync
Also modifies our statesync tests to use EthBlockPolicy. This wasn't
caught because MockBlockPolicy doesn't assert that it's passed `delay`
non-null blocks.

Running `cargo test -p monad-mock-swarm --test forkpoint` yields the
following on the old buggy patch:
```
    Finished `test` profile [optimized + debuginfo] target(s) in 0.33s
     Running tests/forkpoint.rs (target/debug/deps/forkpoint-421b8a4ecaf08933)

running 5 tests
test test_forkpoint_restart_below_all ... ignored
test test_forkpoint_restart_f ... ignored
test test_forkpoint_restart_f_simple_blocksync ... FAILED
test test_forkpoint_restart_f_simple_statesync ... FAILED
test test_forkpoint_restart_f_epoch_boundary_statesync ... FAILED

failures:

---- test_forkpoint_restart_f_simple_blocksync stdout ----
thread 'test_forkpoint_restart_f_simple_blocksync' panicked at monad-bft/monad-eth-block-policy/src/lib.rs:615:13:
assertion `left == right` failed
  left: 11
 right: 5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_forkpoint_restart_f_simple_statesync stdout ----
thread 'test_forkpoint_restart_f_simple_statesync' panicked at monad-bft/monad-eth-block-policy/src/lib.rs:615:13:
assertion `left == right` failed
  left: 159
 right: 5

---- test_forkpoint_restart_f_epoch_boundary_statesync stdout ----
thread 'test_forkpoint_restart_f_epoch_boundary_statesync' panicked at monad-bft/monad-eth-block-policy/src/lib.rs:615:13:
assertion `left == right` failed
  left: 276
 right: 19

failures:
    test_forkpoint_restart_f_epoch_boundary_statesync
    test_forkpoint_restart_f_simple_blocksync
    test_forkpoint_restart_f_simple_statesync

test result: FAILED. 0 passed; 3 failed; 2 ignored; 0 measured; 0 filtered out; finished in 0.13s

error: test failed, to rerun pass `-p monad-mock-swarm --test forkpoint`
```