Avoid Dataplane panic in case of unsupportable address family mismatch
On a Dataplane instance bound to an unspecified or a specific IPv4
address, transmitting an UDP datagram to any IPv6 address will currently
panic with:

    thread '<unnamed>' panicked at monad-dataplane/src/udp.rs:149:17:
    send error Address family not supported by protocol (os error 97)

On a Dataplane instance bound to a specific IPv6 address, transmitting
an UDP datagram to any IPv4 address will currently panic with:

    thread '<unnamed>' panicked at monad-dataplane/src/udp.rs:149:17:
    send error Network is unreachable (os error 101)

We don't necessarily want to completely prohibit the use of IPv6
addresses in Dataplane, because certain combinations of IPv4 and IPv6
addressing are possible -- for example, it is possible for a dual-stack
validator to serve an IPv6 full node, and a validator operator might
want to locally set things up that way.

What we want to avoid, however, is having an unsupportable combination
of IPv4 and IPv6 addresses panic!()ing our Dataplane instance.  It
doesn't look like monad-node filters the results of the DNS lookups it
performs to map its validator and full node peer host names to
SocketAddrs, and it may therefore be possible for a rogue validator to
panic every other validator in the network by pointing its own host
name to an IPv6 (AAAA) address record.

This patch adds some checks to avoid panic!()ing on a UDP send error if
that send error is due to an unsupportable address family mismatch, and
if that happens, we will log a debug message instead.  It also adds a
test to exercise all the address combinations that would previously lead
to Dataplane panics.